version: '3.8'

services:
  api:
    build:
      context: .
      target: production
    image: blaiseniyo/assignment-api
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - 80:80
    env_file:
      - .env